### ISSUE TITLE
[HELP] Hosting bot on shell website.

### ISSUE THREAD

**Issue by PanSmuggler** [fhodun/testshoter#19]
Hello.
I want to host this bot on repl. it but there is problem. I don't know how to "npm start" this bot from index.ts file.
Can you describe how to run bot without using console but just index.ts/index.js or whatever file so it run after clicking start

I don't know what i'am doing wrong. You can test it on [https://repl.it ](url)

When i try to run this from shell "npm start" this is output:
`
> testshoter@2.2.1 start /home/runner/ConsiderableVerticalClosedsource
> ts-node -r dotenv/config -r tsconfig-paths/register .

/home/runner/ConsiderableVerticalClosedsource/src/discord/commands/index.ts:9
  throw new Error(
        ^
Error: COMMAND_PREFIX is not defined in .env, default value is '>'
    at Object.<anonymous> (/home/runner/ConsiderableVerticalClosedsource/src/discord/commands/index.ts:9:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/home/runner/ConsiderableVerticalClosedsource/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/runner/ConsiderableVerticalClosedsource/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testshoter@2.2.1 start: `ts-node -r dotenv/config -r tsconfig-paths/register .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the testshoter@2.2.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

`

**Comment by fhodun** [comment]
I've never used repl.it, but I checked that and you just must manualy set token and prefix in `./src/discord/index.ts` and preifx in `./src/discord/commands/index.ts` like that:
```const commandPrefix = "<your_token>";``` instead of ```const commandPrefix = process.env.COMMAND_PREFIX;```
